### ISSUE TITLE
Add package to PyPI

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#35]
We should [upload our package to PyPI](https://packaging.python.org/en/latest/tutorials/packaging-projects/) so it can be `pip install`ed easily (including with Anaconda).

**Comment by bobmyhill** [comment]
This checklist should be completed for every release of terratools

- [ ] Check new version can be used non-locally (`python -m pip install .`, then run from another directory)
- [ ] Open zenodo, start new version, reserve DOI (currently at the top of Basic Information)
- [ ] New branch (terratools-Major.Minor)
- [ ] Bump version number in new branch (in terratools/version.py)
- [ ] Update changelog.txt with major changes since the last release.
- [ ] Update setup.py (if necessary, probably only Python versions need checking (as we've checked the installation works above), but might be worth checking that `sudo python setup.py sdist bdist_wheel` works without errors)
- [ ] Update new link to the zenodo version (using the new reserved DOI) in terratools/__init__.py
- [ ] Update new link to the zenodo version (using the new reserved DOI) in docs/index.rst
- [ ] Update new badge link to zenodo (using the new reserved DOI) in Readme.md
- [ ] Push new branch to Github upstream terratools-Major.Minor (*not* master)
- [ ] Make release on Github using upstream terratools-Major.Minor branch
- [ ] Make release commit (tag, not branch) active on readthedocs (you'll need to build from master first so that ReadTheDocs finds the new release tag)
- [ ] Build documentation on readthedocs
- [ ] Download zip file
- [ ] Upload new zip file to zenodo, fill in details on website (including new link to ReadTheDocs)
- [ ] Save and publish in zenodo
- [ ] Update GitHub release with new zip files and link to the ReadTheDocs documentation
- [ ] Push release to Pypi (from clean directory, correct branch):
 1) sudo python setup.py sdist bdist_wheel (sudo unfortunately required)
 2) twine check dist/* (to check zip and wheel)
 3) twine upload --repository-url https://test.pypi.org/legacy/ dist/* (to test upload, can get password from the pypi website)
 4) twine upload dist/* (the final upload to Pypi)
- [ ] Merge upstream terratools-Major.Minor branch to master
- [ ] Bump version numbers in version.py on upstream master 
 - version=[Major].[Minor+1].0pre
 - short_version=[Major].[Minor+1].0
- [ ] Check and update homepage (especially the downloads section and the zenodo links)

**Comment by anowacki** [comment]
Wow, comprehensive!  A lot of the effort seems to be Zenodo-related.  Maybe we don't need to do the Zenodo stuff every time?  Or can that be automated?  What about patch releases?

Does ReadTheDocs have a generic 'latest' URL to use rather than needing to update each time?

**Comment by bobmyhill** [comment]
It still needs a few tweaks to make it appropriate for terratools. The whole procedure should take about 2 hours.

The zenodo stuff provides a unique DOI for each version. We don't need to do it, but once it's done once it doesn't take very long to update. I don't think zenodo provides an API to automate this, but I could be wrong.

Yes, readthedocs automatically updates the docs from main, and any other branches we choose. The additional work above makes sure that there are docs for each released version, because the development branch may have different tools from the pypi release.

**Comment by andreww** [comment]
Wait on next milestone

**Comment by jamespanton93** [comment]
v1.0.0 is now on PyPi and we have a DOI through Zenodo: [10.5281/zenodo.10797185](https://zenodo.org/doi/10.5281/zenodo.10797185).

Thanks for the checklist Bob, I would have been very lost without it. I will close the issue but will certainly be referring back to this whenever we need to advance a version again.
